---
resources:
- name: source
  type: git
  source:
    uri: ((git_repository_url))
    private_key: ((git_private_key))
    ignore_paths:
    - RELEASE_NOTES.md

# - name: release-notes
#   type: git
#   source:
#     uri: ((git_repository_url))
#     private_key: ((git_private_key))
#     paths:
#     - RELEASE_NOTES.md

- name: cf-cli
  type: github-release
  source:
    repository: cli
    owner: cloudfoundry
    access_token: ((github_access_token))

- name: draft-releases
  type: github-release
  source:
    repository: download_droplet_plugin
    owner: krujos
    access_token: ((github_access_token))
    drafts: true

# - name: plugin-site
#   type: git
#   source:
#     uri: ((plugin_repo_git_url))
#     private_key: ((git_private_key))

- name: version
  type: semver
  source:
    initial_version: '1.0.1'
    driver: s3
    bucket: ((s3_version_bucket))
    key: ((s3_version_file))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    region_name: ((s3_region))

jobs:
- name: build
  public: true
  plan:
  - aggregate:
    - get: source
      trigger: true
    - get: cf-cli
      trigger: true
    - get: version
      params: {bump: patch}
  - task: ensure-dependencies
    file: source/ci/tasks/ensure-dependencies.yml
  - task: run-tests
    file: source/ci/tasks/run-unit-tests.yml
  - task: build-plugin
    file: source/ci/tasks/build-plugin.yml
  - task: prepare-draft-release
    file: source/ci/tasks/prepare-draft-release.yml
  - put: draft-releases
    params:
      name: prepared-release/name
      tag: prepared-release/tag
      commitish: prepared-release/commit
      body: prepared-release/body
      globs: [ prepared-release/built/* ]
  - put: version
    params: { file: version/number }
