---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: version
- name: tested
  path: go/src/github.com/krujos/download_droplet_plugin

outputs:
- name: built-plugins

run:
  path: go/src/github.com/krujos/download_droplet_plugin/ci/tasks/build-plugin.sh
